import { ebookItems } from '../schema/ebook_items';
import { sqliteDb as db } from "../index";

export async function seedEbooks() {
  const ebooks = [
    // 中文电子书（部分保留）
    {
      id: 'ebook-1',
      name: 'JavaScript 精粹',
      description: '深入浅出 JavaScript 核心机制',
      author: 'Douglas Crockford',
      publisher: '电子工业出版社',
      publishDate: '2018-03-01',
      isbn: '9787121347989',
      price: 19.9,
      originalPrice: 39.9,
      quantity: 100,
      image: '/images/ebooks/js.jpg',
      category: '编程',
      slug: 'javascript-essentials',
      pageCount: 320,
      format: 'PDF',
      language: 'zh',
      fileUrl: '/files/ebooks/js.pdf',
      sampleUrl: '/files/ebooks/js-sample.pdf',
      tags: 'JavaScript,编程,前端',
      rating: 4.8,
      salesCount: 1200,
      viewCount: 3500
    },
    // 英文电子书
    {
      id: 'ebook-en-1',
      name: 'JavaScript: The Good Parts',
      description: 'A deep dive into the core mechanisms of JavaScript.',
      author: 'Douglas Crockford',
      publisher: 'O’Reilly Media',
      publishDate: '2008-05-01',
      isbn: '9780596517748',
      price: 25.5,
      originalPrice: 45.0,
      quantity: 80,
      image: '/images/ebooks/js-en.jpg',
      category: 'Programming',
      slug: 'javascript-the-good-parts',
      pageCount: 176,
      format: 'PDF',
      language: 'en',
      fileUrl: '/files/ebooks/js-en.pdf',
      sampleUrl: '/files/ebooks/js-en-sample.pdf',
      tags: 'JavaScript,Programming,Frontend',
      rating: 4.7,
      salesCount: 900,
      viewCount: 2200
    },
    {
      id: 'ebook-en-2',
      name: 'Python Data Analysis',
      description: 'Practical data analysis and visualization with Python.',
      author: 'Wes McKinney',
      publisher: 'O’Reilly Media',
      publishDate: '2017-10-01',
      isbn: '9781491957660',
      price: 32.0,
      originalPrice: 60.0,
      quantity: 60,
      image: '/images/ebooks/python-en.jpg',
      category: 'Data Science',
      slug: 'python-data-analysis-en',
      pageCount: 500,
      format: 'EPUB',
      language: 'en',
      fileUrl: '/files/ebooks/python-en.epub',
      sampleUrl: '/files/ebooks/python-en-sample.epub',
      tags: 'Python,Data Analysis,Data Science',
      rating: 4.8,
      salesCount: 1100,
      viewCount: 2800
    },
    {
      id: 'ebook-en-3',
      name: 'Deep Learning',
      description: 'An introduction to deep learning fundamentals and applications.',
      author: 'Ian Goodfellow',
      publisher: 'MIT Press',
      publishDate: '2016-11-18',
      isbn: '9780262035613',
      price: 40.0,
      originalPrice: 80.0,
      quantity: 40,
      image: '/images/ebooks/dl-en.jpg',
      category: 'Artificial Intelligence',
      slug: 'deep-learning-en',
      pageCount: 800,
      format: 'PDF',
      language: 'en',
      fileUrl: '/files/ebooks/dl-en.pdf',
      sampleUrl: '/files/ebooks/dl-en-sample.pdf',
      tags: 'Deep Learning,AI,Neural Networks',
      rating: 4.9,
      salesCount: 950,
      viewCount: 2000
    },
    {
      id: 'ebook-en-4',
      name: 'Clean Code',
      description: 'A Handbook of Agile Software Craftsmanship.',
      author: 'Robert C. Martin',
      publisher: 'Prentice Hall',
      publishDate: '2008-08-01',
      isbn: '9780132350884',
      price: 29.9,
      originalPrice: 59.9,
      quantity: 70,
      image: '/images/ebooks/clean-code-en.jpg',
      category: 'Software Engineering',
      slug: 'clean-code-en',
      pageCount: 464,
      format: 'PDF',
      language: 'en',
      fileUrl: '/files/ebooks/clean-code-en.pdf',
      sampleUrl: '/files/ebooks/clean-code-en-sample.pdf',
      tags: 'Clean Code,Software,Engineering',
      rating: 4.8,
      salesCount: 1200,
      viewCount: 2500
    },
    {
      id: 'ebook-en-5',
      name: 'Design Patterns: Elements of Reusable Object-Oriented Software',
      description: 'The classic book on design patterns in software engineering.',
      author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
      publisher: 'Addison-Wesley',
      publishDate: '1994-10-31',
      isbn: '9780201633610',
      price: 35.0,
      originalPrice: 70.0,
      quantity: 50,
      image: '/images/ebooks/design-patterns-en.jpg',
      category: 'Software Engineering',
      slug: 'design-patterns-en',
      pageCount: 395,
      format: 'PDF',
      language: 'en',
      fileUrl: '/files/ebooks/design-patterns-en.pdf',
      sampleUrl: '/files/ebooks/design-patterns-en-sample.pdf',
      tags: 'Design Patterns,Software,Engineering',
      rating: 4.7,
      salesCount: 800,
      viewCount: 1800
    },
    // 多语种电子书
    {
      id: 'ebook-multi-1',
      name: 'Le Petit Prince',
      description: 'Le chef-d’œuvre de la littérature française moderne.',
      author: 'Antoine de Saint-Exupéry',
      publisher: 'Gallimard',
      publishDate: '1943-04-06',
      isbn: '9782070612758',
      price: 18.0,
      originalPrice: 36.0,
      quantity: 40,
      image: '/images/ebooks/le-petit-prince-fr.jpg',
      category: 'Literature',
      slug: 'le-petit-prince-fr',
      pageCount: 96,
      format: 'EPUB',
      language: 'fr',
      fileUrl: '/files/ebooks/le-petit-prince-fr.epub',
      sampleUrl: '/files/ebooks/le-petit-prince-fr-sample.epub',
      tags: 'French,Classic,Literature',
      rating: 4.9,
      salesCount: 2000,
      viewCount: 3500
    },
    {
      id: 'ebook-multi-2',
      name: 'Cien años de soledad',
      description: 'La obra maestra de Gabriel García Márquez.',
      author: 'Gabriel García Márquez',
      publisher: 'Editorial Sudamericana',
      publishDate: '1967-06-05',
      isbn: '9780307474728',
      price: 22.0,
      originalPrice: 44.0,
      quantity: 30,
      image: '/images/ebooks/one-hundred-years-es.jpg',
      category: 'Literature',
      slug: 'cien-anos-soledad-es',
      pageCount: 432,
      format: 'PDF',
      language: 'es',
      fileUrl: '/files/ebooks/one-hundred-years-es.pdf',
      sampleUrl: '/files/ebooks/one-hundred-years-es-sample.pdf',
      tags: 'Spanish,Classic,Literature',
      rating: 4.8,
      salesCount: 1800,
      viewCount: 3000
    },
    {
      id: 'ebook-multi-3',
      name: 'Der Steppenwolf',
      description: 'Ein Klassiker der deutschen Literatur.',
      author: 'Hermann Hesse',
      publisher: 'S. Fischer Verlag',
      publishDate: '1927-06-01',
      isbn: '9783596905242',
      price: 20.0,
      originalPrice: 40.0,
      quantity: 25,
      image: '/images/ebooks/steppenwolf-de.jpg',
      category: 'Literature',
      slug: 'steppenwolf-de',
      pageCount: 320,
      format: 'EPUB',
      language: 'de',
      fileUrl: '/files/ebooks/steppenwolf-de.epub',
      sampleUrl: '/files/ebooks/steppenwolf-de-sample.epub',
      tags: 'German,Classic,Literature',
      rating: 4.6,
      salesCount: 1200,
      viewCount: 2000
    }
  ];
  for (const ebook of ebooks) {
    await db.insert(ebookItems).values(ebook).run();
  }
}

// 可在主 seed 文件中调用 seedEbooks()
