import { gameItems } from '../schema/game_items';
import { sqliteDb as db } from '../index';
import { nanoid } from 'nanoid';

export async function seedGameItems() {
  await db.delete(gameItems);
  const data = [
    {
      id: nanoid(),
      name: '象棋大师',
      description: '经典中国象棋游戏',
      price: 0,
      quantity: 1000,
      image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=400&q=80',
      category: '棋牌',
      slug: 'chess-master-zh',
      locale: 'zh',
      tags: '象棋,棋牌,策略',
      gameGenre: '棋类',
      multiplayer: true,
      platform: 'Web',
      minSystemRequirements: '浏览器',
    },
    {
      id: nanoid(),
      name: 'Chess Master',
      description: 'Classic chess game',
      price: 0,
      quantity: 1000,
      image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=400&q=80',
      category: 'Board',
      slug: 'chess-master',
      locale: 'en',
      tags: 'chess,board,strategy',
      gameGenre: 'Board',
      multiplayer: true,
      platform: 'Web',
      minSystemRequirements: 'Browser',
    },
    {
      id: nanoid(),
      name: 'Sudoku Pro',
      description: 'A challenging sudoku puzzle game',
      price: 0,
      quantity: 500,
      image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
      category: 'Puzzle',
      slug: 'sudoku-pro',
      locale: 'en',
      tags: 'sudoku,puzzle,logic',
      gameGenre: 'Puzzle',
      multiplayer: false,
      platform: 'Web',
      minSystemRequirements: 'Browser',
    },
    {
      id: nanoid(),
      name: '数独大师',
      description: '益智数独游戏',
      price: 0,
      quantity: 500,
      image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
      category: '益智',
      slug: 'sudoku-pro-zh',
      locale: 'zh',
      tags: '数独,益智,逻辑',
      gameGenre: '益智',
      multiplayer: false,
      platform: 'Web',
      minSystemRequirements: '浏览器',
    },
    {
      id: nanoid(),
      name: '2048',
      description: 'Classic 2048 number puzzle',
      price: 0,
      quantity: 800,
      image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
      category: 'Puzzle',
      slug: '2048',
      locale: 'en',
      tags: '2048,puzzle,number',
      gameGenre: 'Puzzle',
      multiplayer: false,
      platform: 'Web',
      minSystemRequirements: 'Browser',
    },
    {
      id: nanoid(),
      name: '2048中文版',
      description: '经典数字合成益智游戏',
      price: 0,
      quantity: 800,
      image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=400&q=80',
      category: '益智',
      slug: '2048-zh',
      locale: 'zh',
      tags: '2048,益智,数字',
      gameGenre: '益智',
      multiplayer: false,
      platform: 'Web',
      minSystemRequirements: '浏览器',
    },
    {
      id: nanoid(),
      name: 'Tic Tac Toe',
      description: 'Classic tic tac toe game',
      price: 0,
      quantity: 1000,
      image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
      category: 'Board',
      slug: 'tic-tac-toe',
      locale: 'en',
      tags: 'tictactoe,board,casual',
      gameGenre: 'Board',
      multiplayer: true,
      platform: 'Web',
      minSystemRequirements: 'Browser',
    },
    {
      id: nanoid(),
      name: '井字棋',
      description: '经典井字棋游戏',
      price: 0,
      quantity: 1000,
      image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
      category: '棋类',
      slug: 'tic-tac-toe-zh',
      locale: 'zh',
      tags: '井字棋,棋类,休闲',
      gameGenre: '棋类',
      multiplayer: true,
      platform: 'Web',
      minSystemRequirements: '浏览器',
    },
    {
      id: nanoid(),
      name: 'Space Invaders',
      description: 'Retro space shooting game',
      price: 0,
      quantity: 300,
      image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
      category: 'Arcade',
      slug: 'space-invaders',
      locale: 'en',
      tags: 'arcade,shooter,retro',
      gameGenre: 'Arcade',
      multiplayer: false,
      platform: 'Web',
      minSystemRequirements: 'Browser',
    },
    {
      id: nanoid(),
      name: '太空侵略者',
      description: '复古太空射击游戏',
      price: 0,
      quantity: 300,
      image: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
      category: '街机',
      slug: 'space-invaders-zh',
      locale: 'zh',
      tags: '街机,射击,复古',
      gameGenre: '街机',
      multiplayer: false,
      platform: 'Web',
      minSystemRequirements: '浏览器',
    },
  ];
  for (const item of data) {
    await db.insert(gameItems).values(item).run();
  }
}
